/usr/libexec/qemu-kvm \
-name 'avocado-vt-vm1'  \
-sandbox off  \
-machine pc  \
-nodefaults  \
-vga cirrus  \
-chardev socket,id=qmp_id_qmpmonitor1,path=/var/tmp/monitor-qmpmonitor,server,nowait \
-mon chardev=qmp_id_qmpmonitor1,mode=control  \
-chardev socket,id=qmp_id_catch_monitor,path=/var/tmp/monitor-catch_monitor,server,nowait \
-mon chardev=qmp_id_catch_monitor,mode=control \
-device pvpanic,ioport=0x505,id=idGxcRRS  \
-chardev socket,id=serial_id_serial0,path=/var/tmp/serial-serial,server,nowait \
-device isa-serial,chardev=serial_id_serial0  \
-chardev socket,id=seabioslog_id_20171215-225225-Hig6fSXf,path=/var/tmp/seabios,server,nowait \
-device isa-debugcon,chardev=seabioslog_id_20171215-225225-Hig6fSXf,iobase=0x402 \
-device ich9-usb-ehci1,id=usb1,addr=0x1d.7,multifunction=on,bus=pci.0 \
-device ich9-usb-uhci1,id=usb1.0,multifunction=on,masterbus=usb1.0,addr=0x1d.0,firstport=0,bus=pci.0 \
-device ich9-usb-uhci2,id=usb1.1,multifunction=on,masterbus=usb1.0,addr=0x1d.2,firstport=2,bus=pci.0 \
-device ich9-usb-uhci3,id=usb1.2,multifunction=on,masterbus=usb1.0,addr=0x1d.4,firstport=4,bus=pci.0 \
-device virtio-scsi-pci,id=virtio_scsi_pci0,bus=pci.0,addr=0x3 \
-drive id=drive_image1,if=none,snapshot=off,aio=threads,cache=none,format=qcow2,file=/home/yhong/Project/YhongAutoProject/images/rhel74-64-virtio-scsi.qcow2 \
-device scsi-hd,id=image1,drive=drive_image1 \
-device virtio-net-pci,mac=9a:48:49:4a:4b:4c,id=idtsgoam,vectors=4,netdev=idCCrM4Z,bus=pci.0,addr=0x4  \
-netdev tap,id=idCCrM4Z,vhost=on \
-m 4096  \
-smp 4,cores=1,threads=1,sockets=4  \
-cpu 'SandyBridge',+kvm_pv_unhalt \
-drive id=drive_cd1,if=none,snapshot=off,aio=threads,cache=none,media=cdrom,file=/home/yhong/Project/YhongAutoProject/isos/RHEL-7.3-20161019.0-Workstation-x86_64-dvd1.iso \
-device ide-cd,id=cd1,drive=drive_cd1,bus=ide.0,unit=0 \
-device usb-tablet,id=usb-tablet1,bus=usb1.0,port=1  \
-vnc :0  \
-rtc base=utc,clock=host,driftfix=slew  \
-boot menu=off,strict=off,order=cdn,once=d  \
-no-shutdown \
-enable-kvm \
-monitor stdio
